[pytest]
testpaths = test_scripts
addopts = -v --tb=short -p no:cacheprovider

markers =
    smoke: Smoke test case
    regression: Regression test case
    DataQuality: Data quality test case

log_file = logs/test_results.log
log_file_level = INFO
log_format = %(asctime)s-%(levelname)s-%(message)s
log_date_format = %Y-%m-%d %H:%M:%S